### ISSUE TITLE
Replace usage of `CLLocationManager.locationServicesEnabled()` with `locationManagerDidChangeAuthorization`

### ISSUE THREAD

**Issue by clausjoergensen** [schibsted/account-sdk-ios-web#196]
In Xcode 14 using `CLLocationManager.locationServicesEnabled()` now triggers a warning:

> This method can cause UI unresponsiveness if invoked on the main thread. Instead, consider waiting for the `-locationManagerDidChangeAuthorization:` callback and checking `authorizationStatus` first.

Since the consumers of the SDK can't control when/where this is called, ideally the SDK should just listen to the `locationManagerDidChangeAuthorization` callback as suggested.

**Comment by zamorastp** [comment]
Thank you! I've created a ticket and added it to our backlog.
